---

- name: Gather the interface information using the Ansible Network Collection for Cisco IOS devices. 
  hosts: iosxe
  gather_facts: False
  tags:
    - network_collection
  
  tasks:

    - name: Gather "show ip interface brief" using ansible ios_command module
      ios_command:
        commands: "show ip interface brief"
      register: cli_result

    - name: Display information as list of strings 
      debug:
        msg: "{{cli_result.stdout_lines[0]}}"

    - name: Gather interface information using "ios facts" module 
      ios_facts:
      
    - name: Display "ansible_net_interface" var as structured data.
      debug:
        var: ansible_net_interfaces # There are several other vars in "ios facts" module

- name: Gather the interface information using the Multi-vendor Ansible Modules for Network Automation (ntc-ansible)
  hosts: iosxe
  gather_facts: False
  tags:
    - ntc-ansible
  
  tasks:

    - name: Gather "show interface brief" using ntc-ansible module 
      ntc_show_command: #All this parameters are needed by netmiko, can be added in the inventory file as vars
        connection: ssh
        platform: cisco_ios
        host: "{{ansible_host}}" # var retrieved from inventory files
        command: "show ip interface brief"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
      register: result

    - name: Display information as structured data.
      debug: 
        var: result