---

- name: Using request and ansible.
  connection: local
  hosts: iosxe
  gather_facts: False

  tasks:
    - name: Get interface configuration using stadard Model
      restconf_get:
        content: config
        output: json
        path: data/ietf-interfaces:interfaces
      register: dataout

    - name: Display information as list of strings 
      debug:
        msg: "{{dataout}}"
    
    - name: Create a loopback using Jinja Templating 
      with_items:
        - { name: Loopback102 , description : 'Created by Ansible' , ip_address : 10.99.99.1 , mask: 255.255.255.0 }
      template: src="./ietf_inteface.j2" dest="./output.json"

    - name: Create loopbacks with RESTCONF
      restconf_config:
        method: patch
        format: json
        path: /data/ietf-interfaces:interfaces/interface
        content: "{{ lookup('file','./output.json') | string }}"
      register: results
      ignore_errors: true

    - name: print output
      debug: msg="{{results}}"
 
  